language: haskell
dist: xenial

cache:
  directories:
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.stack-work

env:
  global:
    - STACK_VERSION=2.1.3
    - HPACK_VERSION=0.31.2

matrix:
  fast_finish: true
  include:
    - env: BUILD=stack ARGS="--system-ghc"
      ghc: "8.6.5"

    - env: BUILD=style
      ghc: "8.6.5"

    - env: BUILD=pedantic ARGS="--system-ghc"
      ghc: "8.6.5"

  allow_failures:
    - env: BUILD=style
    - env: BUILD=pedantic ARGS="--system-ghc"

before_install:
  - case "$BUILD" in
      style)
        export PATH="$TRAVIS_BUILD_DIR"/hlint:$PATH
        ;;
      *)
        export PATH="$HOME"/.local/bin:$PATH
        ;;
    esac

install:
- |
  set -ex
  case "$BUILD" in
    style)
      curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s -- --version
      ;;
    *)
      mkdir -p $HOME/.local/bin

      travis_retry curl -sL https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

      travis_retry stack upgrade --binary-version=$STACK_VERSION

      stack --numeric-version
      stack --hpack-numeric-version
      ghc --version

      stack install tasty-discover
      stack install hspec-discover
      ;;
  esac
  set +ex

script:
- |
  set -ex
  case "$BUILD" in
    style)
      curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
      ;;
    stack)
      stack --no-terminal $ARGS test --no-haddock-deps
      ;;
    pedantic)
      stack --no-terminal $ARGS test --pedantic --no-run-tests
      ;;
  esac
  set +ex

notifications:
  email: false
