version: 2

aliases:
  - &default_env
    environment:
      CACHE_KEY: 1
      STACK_VERSION: 2.1.3
  - &create_cache_key_file
    run:
      name: Create cache control key file
      command: echo $CACHE_KEY > cache_key
  - &restore_build_results
    restore_cache:
      keys:
        - stack-{{ checksum "cache_key" }}-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
        - stack-{{ checksum "cache_key" }}-{{ checksum "stack.yaml" }}
        - stack-{{ checksum "cache_key" }}
  - &save_build_results
      save_cache:
        key: stack-{{ checksum "cache_key" }}-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
        paths:
          - ~/.stack
          - ~/.local/bin
          - .stack-work
  - &display_stack_version
    run:
      name: Display stack version
      command: |
        stack upgrade --binary-version=$STACK_VERSION
        stack --version
jobs:
  build:
    docker:
      - image: quay.io/haskell_works/stack-build-minimal
    <<: *default_env
    steps:
      - checkout
      - *create_cache_key_file
      - *restore_build_results
      - *display_stack_version
      - run:
          name: Install dependencies
          command: stack test -j 1 --only-dependencies --no-terminal --no-run-tests
          no_output_timeout: 120m
      - run:
          name: before run
          command: |
            stack install tasty-discover
            stack install hspec-discover
      - run:
          name: Run stack test
          command: stack --no-terminal test --no-haddock-deps
      - run:
          name: Run stack test --pedantic
          command: |
            stack clean
            stack --no-terminal test --pedantic --no-run-tests
      - run:
          name: Run HLint
          command: |
            curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s -- --version
            curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
      - *save_build_results
